### ISSUE TITLE
Subtask UI

### ISSUE THREAD

**Issue by pathikrit** [coatue/airflow#140]
![image](https://user-images.githubusercontent.com/899219/68228697-e5c35480-ffc3-11e9-81cb-c5350ea0aed8.png)

* [x] Break up into 2 tabs: Coatue UI/Original

The Coatue UI has just 2 buttons
* [x] Link to Cloudwatch Logs
* [ ] Run this and all downstream
* [ ] Run this and no downstream

**Comment by pathikrit** [comment]
Not showing cloudwatch logs:
![image](https://user-images.githubusercontent.com/899219/70100707-955e0780-1600-11ea-9b4a-e3c8d84db5f3.png)

**Comment by skim-coatue** [comment]
Ah we currently push the log url to XCOM  after the task is complete. I'll add it as part of the task polling.
